questions = ([
    # ART HISTORY
    {"topic": "Art History", 
     "qns": "Who painted the Mona Lisa?", 
     "options": ["Vincent van Gogh", "Michelangelo", "Leonardo da Vinci", "Claude Monet"], 
     "Correct Ans": 3,
     "hint": "This Renaissance artist was also an inventor and scientist."},

    {"topic": "Art History", 
     "qns": "Which art movement is Salvador Dalí associated with?", 
     "options": ["Cubism", "Surrealism", "Impressionism", "Baroque"], 
     "Correct Ans": 2,
     "hint": "This movement focused on dreamlike and irrational imagery."},

    {"topic": "Art History", 
     "qns": "What is the name of Michelangelo’s famous fresco on the ceiling of the Sistine Chapel?", 
     "options": ["The Last Supper", "The Birth of Venus", "The Creation of Adam", "Starry Night"], 
     "Correct Ans": 3,
     "hint": "It depicts God reaching out to touch the hand of man."},

    {"topic": "Art History", 
     "qns": "Which artist is known for cutting off part of his own ear?", 
     "options": ["Pablo Picasso", "Edvard Munch", "Vincent van Gogh", "Paul Cézanne"], 
     "Correct Ans": 3,
     "hint": "He painted 'Starry Night' and struggled with mental health issues."},

    {"topic": "Art History", 
     "qns": "Which painting is famous for its mysterious smile?", 
     "options": ["The Scream", "The Mona Lisa", "Girl with a Pearl Earring", "The Persistence of Memory"], 
     "Correct Ans": 2,
     "hint": "It was painted by Leonardo da Vinci."},

    {"topic": "Art History", 
     "qns": "Who painted 'The Starry Night'?", 
     "options": ["Claude Monet", "Vincent van Gogh", "Henri Matisse", "Francisco Goya"], 
     "Correct Ans": 2,
     "hint": "This artist often used thick, swirling brushstrokes."},

    {"topic": "Art History", 
     "qns": "Which art movement is Claude Monet considered a founder of?", 
     "options": ["Expressionism", "Dadaism", "Impressionism", "Realism"], 
     "Correct Ans": 3,
     "hint": "This movement is known for capturing light and atmosphere."},

    {"topic": "Art History", 
     "qns": "Which ancient civilization is known for its pyramid paintings and sculptures?", 
     "options": ["Greek", "Egyptian", "Roman", "Mesopotamian"], 
     "Correct Ans": 2,
     "hint": "They built the pyramids and decorated tombs with murals."},

    {"topic": "Art History", 
     "qns": "Which artist is famous for painting 'Guernica'?", 
     "options": ["Diego Rivera", "Salvador Dalí", "Pablo Picasso", "Francisco Goya"], 
     "Correct Ans": 3,
     "hint": "He co-founded the Cubist movement and painted in response to war."},

    {"topic": "Art History", 
     "qns": "What material was primarily used for sculptures in Ancient Greece?", 
     "options": ["Marble", "Bronze", "Clay", "Wood"], 
     "Correct Ans": 1,
     "hint": "Many famous statues, like the Venus de Milo, were made from this material."},

    {"topic": "Art History", 
     "qns": "Which female artist painted 'The Two Fridas'?", 
     "options": ["Mary Cassatt", "Georgia O’Keeffe", "Frida Kahlo", "Artemisia Gentileschi"], 
     "Correct Ans": 3,
     "hint": "She was a Mexican artist known for self-portraits."},

    {"topic": "Art History", 
     "qns": "Which country was home to the Renaissance art movement?", 
     "options": ["France", "Germany", "Italy", "Spain"], 
     "Correct Ans": 3,
     "hint": "This country was the birthplace of Michelangelo, Leonardo da Vinci, and Raphael."},

    {"topic": "Art History", 
     "qns": "What is the primary characteristic of Cubism?", 
     "options": ["Use of dreamlike imagery", "Focus on light and color", "Breaking objects into geometric shapes", "Highly realistic portraits"], 
     "Correct Ans": 3,
     "hint": "It was pioneered by Picasso and Braque."},

    {"topic": "Art History", 
     "qns": "What famous painting features a melting clock?", 
     "options": ["The Persistence of Memory", "The Scream", "American Gothic", "The Last Supper"], 
     "Correct Ans": 1,
     "hint": "It was painted by Salvador Dalí."},

    {"topic": "Art History", 
     "qns": "What is the name of the prehistoric cave paintings found in France?", 
     "options": ["Lascaux", "Altamira", "Chauvet", "Stonehenge"], 
     "Correct Ans": 1,
     "hint": "These caves contain some of the oldest known artwork, dating back over 17,000 years."},
    
    # MUSIC & BANDS
    {"topic": "Music and Bands", 
     "qns": "Which band released the song 'Bohemian Rhapsody'?", 
     "options": ["The Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], 
     "Correct Ans": 2,
     "hint": "Their lead singer was Freddie Mercury."},

    {"topic": "Music and Bands", 
     "qns": "Which song features the lyrics 'Is this the real life? Is this just fantasy?'", 
     "options": ["Stairway to Heaven", "Bohemian Rhapsody", "Hotel California", "Imagine"], 
     "Correct Ans": 2,
     "hint": "It’s one of Queen’s most famous songs."},

    {"topic": "Music and Bands", 
     "qns": "What genre of music is Metallica primarily known for?", 
     "options": ["Punk Rock", "Heavy Metal", "Pop", "Jazz"], 
     "Correct Ans": 2,
     "hint": "They are one of the 'Big Four' bands of thrash metal."},

    {"topic": "Music and Bands", 
     "qns": "Which rapper released the album 'To Pimp a Butterfly'?", 
     "options": ["Drake", "J. Cole", "Kendrick Lamar", "Kanye West"], 
     "Correct Ans": 3,
     "hint": "He won the Pulitzer Prize for Music."},

    {"topic": "Music and Bands", 
     "qns": "Which band released the album 'The Dark Side of the Moon'?", 
     "options": ["Pink Floyd", "The Rolling Stones", "The Doors", "Fleetwood Mac"], 
     "Correct Ans": 1,
     "hint": "This album cover features a prism and a rainbow."},

    {"topic": "Music and Bands", 
     "qns": "Which song starts with the lyrics 'Hello, it's me'?", 
     "options": ["Someone Like You", "Rolling in the Deep", "Hello", "When We Were Young"], 
     "Correct Ans": 3,
     "hint": "It’s one of Adele’s biggest hits."},

    {"topic": "Music and Bands", 
     "qns": "What was the name of The Beatles' drummer?", 
     "options": ["Paul McCartney", "George Harrison", "Ringo Starr", "John Lennon"], 
     "Correct Ans": 3,
     "hint": "His real name is Richard Starkey."},

    {"topic": "Music and Bands", 
     "qns": "Which artist performed 'Purple Rain'?", 
     "options": ["Michael Jackson", "Prince", "David Bowie", "Stevie Wonder"], 
     "Correct Ans": 2,
     "hint": "He was known for his flamboyant style and guitar skills."},

    {"topic": "Music and Bands", 
     "qns": "Which band released the album 'American Idiot'?", 
     "options": ["Nirvana", "Green Day", "The Offspring", "Blink-182"], 
     "Correct Ans": 2,
     "hint": "This punk rock band is led by Billie Joe Armstrong."},

    {"topic": "Music and Bands", 
     "qns": "Which artist is known for wearing a meat dress at the MTV VMAs?", 
     "options": ["Katy Perry", "Lady Gaga", "Madonna", "Nicki Minaj"], 
     "Correct Ans": 2,
     "hint": "She also performed 'Bad Romance' and 'Poker Face'."},

    {"topic": "Music and Bands", 
     "qns": "Which rock band features members Jimmy Page and Robert Plant?", 
     "options": ["The Rolling Stones", "AC/DC", "Led Zeppelin", "The Who"], 
     "Correct Ans": 3,
     "hint": "They are famous for 'Stairway to Heaven'."},

    {"topic": "Music and Bands", 
     "qns": "Which rap group released 'Straight Outta Compton'?", 
     "options": ["Public Enemy", "Wu-Tang Clan", "Run-D.M.C.", "N.W.A"], 
     "Correct Ans": 4,
     "hint": "This group included Dr. Dre and Ice Cube."},

    {"topic": "Music and Bands", 
     "qns": "Which song starts with the lyrics 'Don't stop believin' / Hold on to that feelin'?", 
     "options": ["Livin' on a Prayer", "Sweet Child O' Mine", "Don't Stop Believin'", "We Will Rock You"], 
     "Correct Ans": 3,
     "hint": "It's one of Journey’s biggest hits."},

    {"topic": "Music and Bands", 
     "qns": "Which band wrote the song 'Hotel California'?", 
     "options": ["The Eagles", "Fleetwood Mac", "The Doors", "Journey"], 
     "Correct Ans": 1,
     "hint": "This band is known for their smooth rock sound and harmonies."},

    {"topic": "Music and Bands", 
     "qns": "Who is the lead singer of Foo Fighters?", 
     "options": ["Eddie Vedder", "Kurt Cobain", "Dave Grohl", "Chris Cornell"], 
     "Correct Ans": 3,
     "hint": "He was Nirvana’s drummer before forming this band."},

    # BATMAN: ARKHAM ASYLUM & ARKHAM KNIGHT
    {"topic": "Batman: Arkham", 
     "qns": "Who is the main antagonist in *Batman: Arkham Asylum*?", 
     "options": ["The Joker", "Scarecrow", "Bane", "Harley Quinn"], 
     "Correct Ans": 1,
     "hint": "He’s Batman’s most iconic nemesis and is voiced by Mark Hamill."},

    {"topic": "Batman: Arkham", 
     "qns": "What toxin does Scarecrow use to induce fear in *Arkham Asylum*?", 
     "options": ["Joker Gas", "Fear Toxin", "Venom", "Titan Formula"], 
     "Correct Ans": 2,
     "hint": "It’s a gas that causes terrifying hallucinations."},

    {"topic": "Batman: Arkham", 
     "qns": "Which character is revealed to be the Arkham Knight?", 
     "options": ["Tim Drake", "Jason Todd", "Damian Wayne", "Dick Grayson"], 
     "Correct Ans": 2,
     "hint": "He was once Batman’s second Robin."},

    {"topic": "Batman: Arkham", 
     "qns": "What is the name of the prison facility in *Arkham Asylum*?", 
     "options": ["Blackgate", "Arkham City", "Arkham Island", "Arkham Penitentiary"], 
     "Correct Ans": 4,
     "hint": "It’s a section dedicated to containing the most dangerous criminals."},

    {"topic": "Batman: Arkham", 
     "qns": "Which villain manipulates Batman with hallucinations in *Arkham Knight*?", 
     "options": ["Ra’s al Ghul", "The Joker", "The Riddler", "Scarecrow"], 
     "Correct Ans": 4,
     "hint": "He specializes in psychological warfare and fear-based toxins."},

    {"topic": "Batman: Arkham", 
     "qns": "What experimental substance does The Joker inject himself with in *Arkham Asylum*?", 
     "options": ["Fear Gas", "Venom", "Titan Formula", "Joker Toxin"], 
     "Correct Ans": 3,
     "hint": "It’s a powerful serum derived from Bane’s strength-enhancing drug."},

    {"topic": "Batman: Arkham", 
     "qns": "What vehicle is fully playable in *Arkham Knight*?", 
     "options": ["Batplane", "Batcycle", "Batwing", "Batmobile"], 
     "Correct Ans": 4,
     "hint": "It transforms into both a high-speed car and a combat tank."},

    {"topic": "Batman: Arkham", 
     "qns": "Who is the head of security in *Arkham Asylum*?", 
     "options": ["Jim Gordon", "Aaron Cash", "Quincy Sharp", "Lucius Fox"], 
     "Correct Ans": 2,
     "hint": "He has a hook for a hand due to a run-in with Killer Croc."},

    {"topic": "Batman: Arkham", 
     "qns": "Which villain leads the militia in *Arkham Knight*?", 
     "options": ["Deathstroke", "Scarecrow", "Arkham Knight", "Two-Face"], 
     "Correct Ans": 3,
     "hint": "His identity is a major twist in the game’s storyline."},

    {"topic": "Batman: Arkham", 
     "qns": "What is Oracle’s real identity in *Arkham Knight*?", 
     "options": ["Selina Kyle", "Harleen Quinzel", "Barbara Gordon", "Talia al Ghul"], 
     "Correct Ans": 3,
     "hint": "She’s Commissioner Gordon’s daughter and a former Batgirl."},

    {"topic": "Batman: Arkham", 
     "qns": "Which villain has hundreds of riddles scattered across Gotham in *Arkham Knight*?", 
     "options": ["The Joker", "Harley Quinn", "The Riddler", "Mr. Freeze"], 
     "Correct Ans": 3,
     "hint": "He’s obsessed with intellectual superiority and puzzles."},

    {"topic": "Batman: Arkham", 
     "qns": "Who assists Batman with technological upgrades in *Arkham Knight*?", 
     "options": ["Alfred", "Tim Drake", "Lucius Fox", "Barbara Gordon"], 
     "Correct Ans": 3,
     "hint": "He’s the CEO of Wayne Enterprises and a technology expert."},

    {"topic": "Batman: Arkham", 
     "qns": "What hallucinatory figure haunts Batman throughout *Arkham Knight*?", 
     "options": ["Scarecrow", "The Joker", "Ra’s al Ghul", "Hush"], 
     "Correct Ans": 2,
     "hint": "This character died in a previous game but lingers in Batman’s mind."},

    {"topic": "Batman: Arkham", 
     "qns": "Which villain runs the underground fight club in *Arkham Asylum*?", 
     "options": ["Bane", "The Penguin", "Killer Croc", "Zsasz"], 
     "Correct Ans": 1,
     "hint": "He is known for his superhuman strength powered by Venom."},

    {"topic": "Batman: Arkham", 
     "qns": "Which ally is kidnapped by Scarecrow in *Arkham Knight*?", 
     "options": ["Lucius Fox", "Commissioner Gordon", "Catwoman", "Barbara Gordon"], 
     "Correct Ans": 4,
     "hint": "She operates under the alias 'Oracle.'"},
])
