questions = [
    # RETRO GAMING
    {"topic": "Retro Gaming", 
     "qns": "Which game is considered the first-ever video game?", 
     "options": ["Pong", "Pac-Man", "Spacewar!", "Tennis for Two"], 
     "Correct Ans": 4,
     "hint": "It was created in 1958 and simulated a sport."},

    {"topic": "Retro Gaming", 
     "qns": "What was the first home video game console?", 
     "options": ["Atari 2600", "Magnavox Odyssey", "NES", "ColecoVision"], 
     "Correct Ans": 2,
     "hint": "Released in 1972, it predates Atari’s consoles."},

    {"topic": "Retro Gaming", 
     "qns": "Which company created the character Mega Man?", 
     "options": ["Konami", "Nintendo", "Capcom", "Sega"], 
     "Correct Ans": 3,
     "hint": "This company also created Street Fighter."},

    {"topic": "Retro Gaming", 
     "qns": "What is the name of the princess in the original Donkey Kong?", 
     "options": ["Peach", "Daisy", "Zelda", "Pauline"], 
     "Correct Ans": 4,
     "hint": "She was Mario’s first damsel in distress."},

    {"topic": "Retro Gaming", 
     "qns": "Which game popularized the 'Konami Code' cheat?", 
     "options": ["Contra", "Gradius", "Castlevania", "Metal Gear"], 
     "Correct Ans": 1,
     "hint": "It’s a side-scrolling shooter known for co-op play."},

    {"topic": "Retro Gaming", 
     "qns": "Which character is the protagonist of the Metroid series?", 
     "options": ["Link", "Samus Aran", "Fox McCloud", "Simon Belmont"], 
     "Correct Ans": 2,
     "hint": "She’s a bounty hunter in a power suit."},

    {"topic": "Retro Gaming", 
     "qns": "What was the final game released for the NES?", 
     "options": ["Kirby’s Adventure", "Wario’s Woods", "Super Mario Bros. 3", "Mega Man 6"], 
     "Correct Ans": 2,
     "hint": "It came out in 1994 and starred a familiar enemy."},

    {"topic": "Retro Gaming", 
     "qns": "Which arcade game involves a frog crossing traffic and rivers?", 
     "options": ["Centipede", "Frogger", "Q*bert", "Dig Dug"], 
     "Correct Ans": 2,
     "hint": "It was developed by Konami in 1981."},

    {"topic": "Retro Gaming", 
     "qns": "What is the main objective in the game Tetris?", 
     "options": ["Collecting coins", "Fitting shapes", "Saving princesses", "Avoiding ghosts"], 
     "Correct Ans": 2,
     "hint": "It involves stacking falling tetrominoes."},

    {"topic": "Retro Gaming", 
     "qns": "Which classic RPG features classes like Warrior, Thief, and Mage?", 
     "options": ["EarthBound", "Dragon Quest", "Final Fantasy", "Phantasy Star"], 
     "Correct Ans": 3,
     "hint": "It’s a long-running series by Square Enix."},

    {"topic": "Retro Gaming", 
     "qns": "Which company developed the Sega Genesis?", 
     "options": ["Sega", "Nintendo", "Atari", "Sony"], 
     "Correct Ans": 1,
     "hint": "They also created Sonic the Hedgehog."},

    {"topic": "Retro Gaming", 
     "qns": "What color is the ghost 'Inky' in Pac-Man?", 
     "options": ["Red", "Pink", "Blue", "Orange"], 
     "Correct Ans": 3,
     "hint": "He’s the cool, unpredictable one."},

    {"topic": "Retro Gaming", 
     "qns": "Which game is known for its catchphrase 'Finish Him'?", 
     "options": ["Street Fighter", "Mortal Kombat", "Tekken", "Killer Instinct"], 
     "Correct Ans": 2,
     "hint": "It’s famous for its brutal 'Fatalities'."},

    {"topic": "Retro Gaming", 
     "qns": "What iconic handheld console did Nintendo release in 1989?", 
     "options": ["Game Gear", "Game Boy", "WonderSwan", "Lynx"], 
     "Correct Ans": 2,
     "hint": "It was bundled with Tetris."},

    {"topic": "Retro Gaming", 
     "qns": "Which character was originally called 'Jumpman'?", 
     "options": ["Luigi", "Donkey Kong", "Mario", "Wario"], 
     "Correct Ans": 3,
     "hint": "He’s Nintendo’s most iconic character."},
    
    # APHEX TWIN
    {"topic": "Aphex Twin", 
     "qns": "What is Aphex Twin's real name?", 
     "options": ["Richard D. James", "Tom Jenkinson", "Mike Paradinas", "Chris Cunningham"], 
     "Correct Ans": 1,
     "hint": "His initials are RDJ."},

    {"topic": "Aphex Twin", 
     "qns": "Which album features the track 'Windowlicker'?", 
     "options": ["Drukqs", "Selected Ambient Works 85-92", "Come to Daddy", "Windowlicker EP"], 
     "Correct Ans": 4,
     "hint": "The title of the album is the same as the track."},

    {"topic": "Aphex Twin", 
     "qns": "Which Aphex Twin album is famous for its creepy face on the cover?", 
     "options": ["Syro", "Richard D. James Album", "Drukqs", "Come to Daddy"], 
     "Correct Ans": 2,
     "hint": "It’s named after himself."},

    {"topic": "Aphex Twin", 
     "qns": "Which music video features disturbing children with Aphex Twin’s face?", 
     "options": ["On", "Flim", "Come to Daddy", "Windowlicker"], 
     "Correct Ans": 3,
     "hint": "It’s one of his most iconic and terrifying videos."},

    {"topic": "Aphex Twin", 
     "qns": "Which alias has Aphex Twin released music under?", 
     "options": ["Squarepusher", "AFX", "Boards of Canada", "Venetian Snares"], 
     "Correct Ans": 2,
     "hint": "It’s a shortened form of his primary name."},

    {"topic": "Aphex Twin", 
     "qns": "Which 2014 album marked Aphex Twin’s return after a 13-year break?", 
     "options": ["Drukqs", "Collapse EP", "Syro", "Analord"], 
     "Correct Ans": 3,
     "hint": "It won a Grammy for Best Dance/Electronic Album."},

    {"topic": "Aphex Twin", 
     "qns": "What kind of music is Aphex Twin best known for?", 
     "options": ["Hip-Hop", "Ambient", "Breakcore", "Techno"], 
     "Correct Ans": 4,
     "hint": "He’s famous for pushing experimental electronic sounds."},

    {"topic": "Aphex Twin", 
     "qns": "Which early Aphex Twin album is considered a masterpiece of ambient music?", 
     "options": ["Richard D. James Album", "Syro", "Selected Ambient Works 85-92", "Come to Daddy"], 
     "Correct Ans": 3,
     "hint": "It contains tracks created when he was a teenager."},

    {"topic": "Aphex Twin", 
     "qns": "What piece of equipment is Aphex Twin known for using extensively?", 
     "options": ["Roland TB-303", "Theremin", "Sequentix Cirklon", "Akai MPC"], 
     "Correct Ans": 3,
     "hint": "It’s a rare sequencer for creating complex rhythms."},

    {"topic": "Aphex Twin", 
     "qns": "Which Aphex Twin track is a gentle piano composition?", 
     "options": ["Avril 14th", "Flim", "Ageispolis", "Vordhosbn"], 
     "Correct Ans": 1,
     "hint": "It was famously sampled by Kanye West."},

    {"topic": "Aphex Twin", 
     "qns": "Which label did Aphex Twin co-found?", 
     "options": ["Warp Records", "Planet Mu", "Rephlex Records", "Ninja Tune"], 
     "Correct Ans": 3,
     "hint": "It specialized in releasing experimental music."},

    {"topic": "Aphex Twin", 
     "qns": "Which Aphex Twin project consists of hundreds of unreleased tracks?", 
     "options": ["Analord", "Syro", "Collapse EP", "SoundCloud Dump"], 
     "Correct Ans": 4,
     "hint": "He shared these anonymously online."},

    {"topic": "Aphex Twin", 
     "qns": "Which Aphex Twin album is a double-disc release?", 
     "options": ["Richard D. James Album", "Drukqs", "Syro", "I Care Because You Do"], 
     "Correct Ans": 2,
     "hint": "It combines breakcore with prepared piano pieces."},

    {"topic": "Aphex Twin", 
     "qns": "Which Aphex Twin track famously contains hidden images of his face in the audio spectrum?", 
     "options": ["Come to Daddy", "Windowlicker", "Equation", "Vordhosbn"], 
     "Correct Ans": 3,
     "hint": "The track name suggests math-related themes."},

    {"topic": "Aphex Twin", 
     "qns": "Where did Aphex Twin grow up?", 
     "options": ["Manchester", "London", "Cornwall", "Bristol"], 
     "Correct Ans": 3,
     "hint": "It’s a coastal region in southwest England."},

    # KENDRICK LAMAR
    {"topic": "Kendrick Lamar", 
     "qns": "What is Kendrick Lamar's full name?", 
     "options": ["Kendrick Lamont Carter", "Kendrick Lamar Duckworth", "Kendrick Lionel Davis", "Kendrick Lamar Washington"], 
     "Correct Ans": 2,
     "hint": "His last name is 'Duckworth,' which is also the title of one of his songs."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which city is Kendrick Lamar from?", 
     "options": ["Chicago", "New York", "Compton", "Atlanta"], 
     "Correct Ans": 3,
     "hint": "It's a city in California known for its influence on West Coast hip-hop."},

    {"topic": "Kendrick Lamar", 
     "qns": "What was Kendrick Lamar’s debut studio album?", 
     "options": ["To Pimp a Butterfly", "DAMN.", "good kid, m.A.A.d city", "Section.80"], 
     "Correct Ans": 4,
     "hint": "It was an independent release that came before he joined a major label."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which Kendrick Lamar album won the Pulitzer Prize for Music?", 
     "options": ["To Pimp a Butterfly", "DAMN.", "good kid, m.A.A.d city", "Mr. Morale & the Big Steppers"], 
     "Correct Ans": 2,
     "hint": "It was released in 2017 and includes the hit single 'HUMBLE.'."},

    {"topic": "Kendrick Lamar", 
     "qns": "What is the name of Kendrick Lamar’s rap collective?", 
     "options": ["Odd Future", "Top Dawg Entertainment", "Black Hippy", "Dreamville"], 
     "Correct Ans": 3,
     "hint": "It includes Schoolboy Q, Ab-Soul, and Jay Rock."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which track opens Kendrick Lamar’s album 'To Pimp a Butterfly'?", 
     "options": ["i", "Alright", "Wesley’s Theory", "King Kunta"], 
     "Correct Ans": 3,
     "hint": "The track features funk legend George Clinton."},

    {"topic": "Kendrick Lamar", 
     "qns": "What is the recurring phrase in the song 'Alright'?", 
     "options": ["We gon’ be alright", "I love myself", "Be humble", "Money trees grow"], 
     "Correct Ans": 1,
     "hint": "This phrase became a protest chant during social justice movements."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which Marvel film did Kendrick Lamar curate the soundtrack for?", 
     "options": ["Avengers: Endgame", "Black Panther", "Spider-Man: Homecoming", "Doctor Strange"], 
     "Correct Ans": 2,
     "hint": "It’s a 2018 film about a Wakandan superhero."},

    {"topic": "Kendrick Lamar", 
     "qns": "What is the name of the final track on 'DAMN.'?", 
     "options": ["LOVE.", "FEAR.", "DUCKWORTH.", "PRIDE."], 
     "Correct Ans": 3,
     "hint": "It shares Kendrick's legal surname."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which producer frequently collaborates with Kendrick Lamar?", 
     "options": ["Metro Boomin", "Hit-Boy", "Flying Lotus", "Sounwave"], 
     "Correct Ans": 4,
     "hint": "He is part of the in-house TDE production team."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which 2012 album features the track 'Swimming Pools (Drank)'?", 
     "options": ["DAMN.", "To Pimp a Butterfly", "good kid, m.A.A.d city", "Section.80"], 
     "Correct Ans": 3,
     "hint": "It’s considered a modern hip-hop classic and a cinematic narrative album."},

    {"topic": "Kendrick Lamar", 
     "qns": "What alias did Kendrick Lamar release music under early in his career?", 
     "options": ["K.Dot", "King Kunta", "Kung Fu Kenny", "Lamarcus"], 
     "Correct Ans": 1,
     "hint": "It’s a shortened form of his first name."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which song earned Kendrick Lamar a Grammy for Best Rap Performance in 2018?", 
     "options": ["DNA.", "LOYALTY.", "HUMBLE.", "LOVE."], 
     "Correct Ans": 3,
     "hint": "It’s known for its commanding hook: 'Sit down, be humble.'."},

    {"topic": "Kendrick Lamar", 
     "qns": "What theme is central to 'good kid, m.A.A.d city'?", 
     "options": ["Love", "Coming of age", "Politics", "Fame"], 
     "Correct Ans": 2,
     "hint": "The album is a semi-autobiographical story about his youth."},

    {"topic": "Kendrick Lamar", 
     "qns": "Which Kendrick Lamar song features the line 'I remember you was conflicted' repeatedly?", 
     "options": ["u", "Mortal Man", "Alright", "These Walls"], 
     "Correct Ans": 2,
     "hint": "It’s the closing track on 'To Pimp a Butterfly.'"}
]
